name: Auto-Run Notebook and Log to WandB

on:  
  push:  
    paths:  
      - '**.py'  
      - '**.ipynb'  
      - '**requirements.txt'  
  pull_request:  
    branches: [ main ]

jobs:
  track_experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install wandb numpy pandas matplotlib scikit-learn seaborn

      - name: Set up WandB API Key
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          wandb login $WANDB_API_KEY

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute your_notebook.ipynb

      - name: Commit and Push Updated Notebook
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add your_notebook.ipynb
          git commit -m "Updated notebook with latest WandB results"
          git push
